"""Added account table

Revision ID: 485dd6dd6963
Revises: 018cf94b39fb
Create Date: 2023-02-21 13:52:52.861459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485dd6dd6963'
down_revision = '018cf94b39fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('admins', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'admins', ['email'])
    op.add_column('answers', sa.Column('question_id', sa.Integer(), nullable=True))
    op.alter_column('answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(None, 'answers', ['title'])
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'questions', ['title'])
    op.create_foreign_key(None, 'questions', 'themes', ['theme_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'themes', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='unique')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='unique')
    op.alter_column('answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('answers', 'question_id')
    op.drop_constraint(None, 'admins', type_='unique')
    op.alter_column('admins', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('admins', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
